### ISSUE TITLE
Sublime doesn't show up in the search bar

### ISSUE THREAD

**Issue by chachmu** [RoboJackets/robocup-images#2]
Currently the only way to find sublime is to right click a file and then go through the list of programs that can open it. Is there a way to lock it to the launcher beforehand or at least make it show up in the search bar?

**Comment by jgkamat** [comment]
This is probably an issue on first statup, probably if you reboot the machine it fixes things. 

Not sure what I can do about this but make people wait for a bit (although this may be a way to trigger this manually).

**Comment by chachmu** [comment]
I definitely had rebooted at least 3 times before trying that, I'm wondering if it doesn't recognize it as a program to display in the search bar until you actually launch it for the first time or something weird like that.

**Comment by jgkamat** [comment]
I'll take a look at it

**Comment by jgkamat** [comment]
I seem to be able to find it on first login (even on the first start). Are you sure you're having this issue?

**Comment by chachmu** [comment]
It definitely didn't show up the first time I searched for it, maybe I just didn't give it enough time to display the results. It shows up every time now.
