### ISSUE TITLE
Make rcon-client

### ISSUE THREAD

**Issue by chachmu** [RoboJackets/robocup-images#3]
It appeared that all of the robocup programs had already been built when I opened them up. This includes sslrefbox but, there is a second program that can be built in sslrefbox in the rcon-client folder. I doubt that many people will use it very often but for the sake of consistency it might be good to prebuild this one too.

**Comment by jgkamat** [comment]
:+1: on this! Whats the command to build it (is it in the same repo)?

This is the only docs I could find, its pretty bad :/
https://robocup-ssl.github.io/ssl-refbox/install.html

**Comment by jgkamat** [comment]
Ah it's here: https://github.com/RoboCup-SSL/ssl-refbox/tree/master/rcon-client

**Comment by chachmu** [comment]
Yeah, just go into rcon-client and run Make

**Comment by jgkamat** [comment]
Fixed in 	19eb9f5
